# Generated by Django 5.2 on 2025-05-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='resim',
            field=models.CharField(verbose_name=200),
        ),
    ]
